### ISSUE TITLE
Bad redirect after login

### ISSUE THREAD

**Issue by wixaw** [uhm-coe/authorizer#103]
Hello
I update ur plugin 3.1.2 to 3.2 and after CAS login we are redirect to site.com/wp-admin/ instead of site.com
After downgrade with wp plugin update authorizer --version=3.1.2  it's works ! 
I use wp 5.8.1 and php 7
Thanks you in advance
William

**Comment by figureone** [comment]
1. Is this from `wp-login.php` or a custom login form?
2. Do you have a `redirect_to` param in the login URL? That's ultimately what will dictate where it will go after authenticating.
3. What external service are you using?

Any other details you can provide are also appreciated.

**Comment by wixaw** [comment]
I use a custom admin link (  with 'WPS Hide Login' plugin ) who redirect siteom/custom_admin to site.com/wp-admin/
I see a redirect param but it's not me who set that
I use CAS provider
I use a custom roles but if i disable i have a same issue 
I looked in your last commits, but I do not find anything

**Comment by figureone** [comment]
Aloha, we added custom code to detect if the WPS Hide Login plugin is being used, and redirect to the home page after login if so. The problem was Authorizer was redirecting back to the login page after logging in, and WPS Hide Login plugin will redirect that to `/wp-admin`.

The fix is included in version `3.2.1` just released.
