### ISSUE TITLE
Unable to test or debug LDAP configuration

### ISSUE THREAD

**Issue by rossigee** [uhm-coe/authorizer#40]
I'm trying to figure out why my LDAP authentication configuration is not working. The exact same configuration works on another instance. I'm looking in the PHP error logs, but there is nothing there.

A closer inspection of the code suggests that if LDAP is configured, but there is a connection failure, that either a WP_Error or null is returned from the 'custom_authenticate_ldap' function, which is then promptly ignored/discarded by the caller. There appears to be no way for the plugin user that has configured LDAP auth to identify if they are missing the LDAP module, or are having some kind of SSL issues or whatever.

Most importantly, the plugin should report WP_Errors (or missing LDAP modules) to the user somehow. IMHO, the best way to do that would be to have a 'test authentication' panel in the admin settings that will call the 'custom_authenticate' method and report success or relevant error messages to the user to help them fix their system settings or plugin configuration.

**Comment by figureone** [comment]
A missing PHP LDAP module is already reported to the user:
https://github.com/uhm-coe/authorizer/blob/master/authorizer.php#L3965

We cannot fail with a WP_Error on LDAP failure, because then you kill WordPress logins. Since LDAP logins share the same login form as WordPress logins, if you misconfigure LDAP, returning a WP_Error there will prevent you from logging into your site entirely. By returning null in the `authenticate` filter, the next function hooked into the filter gets to run. WordPress core hooks in at priority 20.

For quick debugging, you can edit the plugin source and throw some `error_log( print_r( $variable_to_inspect, true ) );` lines in to check LDAP output, or remove the @-silencing of LDAP errors:
https://github.com/uhm-coe/authorizer/blob/master/authorizer.php#L1341

A more user-friendly LDAP testing feature isn't currently on the roadmap, but we can leave this ticket open to track it. As an open source project, pull requests for features are always welcome. ;)

**Comment by figureone** [comment]
Version 3.3.0 includes an ldap test feature in Authorizer Settings.
