### ISSUE TITLE
Filters on LDAP

### ISSUE THREAD

**Issue by svalavuo** [uhm-coe/authorizer#59]
Is there a way to use filters when authenticating against LDAP?

**Comment by pkarjala** [comment]
What is it that you want to accomplish?  There are a number of filters available before / after authentication of any type.  Having more information on your intentions will help us to answer your question.

**Comment by svalavuo** [comment]
Well, I can't find any place to insert my filters. I'd need to authenticate users against LDAP using filter to find all active (not disabled) users and with certain objectClass set. I just can't find a field to type those filters.

**Comment by pkarjala** [comment]
Thank you for the clarification; I apologize for the confusion regarding LDAP filters versus WordPress filters.

You may add an LDAP search filter programmatically by creating a WordPress filter using `authorizer_ldap_search_filter` as the hook.  Please see https://github.com/uhm-coe/authorizer/blob/master/authorizer.php#L1510-L1520 for the location of this hook.  You can read more about adding filters in WordPress at https://developer.wordpress.org/reference/functions/add_filter/.

Otherwise, at this time we do not provide a way to do this through the WordPress Authorizer admin interface.
