### ISSUE TITLE
CAS without creating WordPress accounts

### ISSUE THREAD

**Issue by sdodowil** [uhm-coe/authorizer#84]
Hello, 
Is it possible to enable CAS authentication without the plugin creating wordpress accounts?
 
Our security specialist wants to know if it’s possible for content providers to our multisite to re-authenticate using WordPress login to access the dashboard while CAS only functions as a frontend access tool.

**Comment by pkarjala** [comment]
Hi, thanks for your question!

Yes, this is a supported configuration.

In the Authorizer settings under Multisite, click on the "Login Access" tab, and set "Who can log into the site?" to "Only approved users (Approved external users and all WordPress users)"

Any valid CAS logins that aren't already WordPress users will be logged in the Pending Users list, and you can safely ignore those users if you don't want to give them access.

Please let us know if this answers your question, or if further clarification is needed.

**Comment by sdodowil** [comment]
I don't see the "Login Access" tab
![authorizer](https://user-images.githubusercontent.com/57155048/67807169-84463780-fa51-11e9-8dcf-4989e92a5de4.PNG)

Will users with valid CAS logins that aren't Wordpress users be able to view the frontend site? Because when I select the "Only approved users" option, it doesn't allow for the users to view the frontend unless they are approved.

**Comment by pkarjala** [comment]
I think we should clarify what it is that you are trying to accomplish here; it sounds like you want the following situation:

- Website is not viewable by anyone by default, but there is a log in page
- Website is viewable when a user logs in with CAS, but do not create a WordPress account for them
- Website dashboard is reachable if a user logs in with a WordPress account

Is this correct?  If not, can you please explain the desired user workflow?

If you want to hide the site from the general public, and only have it visible to CAS users, but don’t want the CAS users edit content, then set "Who can view sites in this network?" to “Only logged in users can see the site”,  and set "Who can log in to sites in this network?" to "All authenticated users”, and then set the default role under the External Service tab to an unprivileged one like Subscriber.  This way all new CAS users get Subscriber accounts, and any existing WordPress admins can still use their CAS credentials to log in.

Please note that this will still create a WordPress account for each new CAS user that logs in, but they will not have any permissions beyond Subscriber.

**Comment by sdodowil** [comment]
That's almost accurate except
•	Website is not viewable by anyone by default, but there is a log in page
•	Website is viewable when a user logs in with CAS, but do not create a WordPress account for them
•	Website dashboard is reachable only if a user logs in using WordPress login page (not CAS)

Our security admin basically doesn't want CAS to grant dashboard access to anyone (including those with permissions to manage site)...

**Comment by sdodowil** [comment]
**If you want to hide the site from the general public, and only have it visible to CAS users, but don’t want the CAS users edit content, then set "Who can view sites in this network?" to “Only logged in users can see the site”, and set "Who can log in to sites in this network?" to "All authenticated users”, and then set the default role under the External Service tab to an unprivileged one like Subscriber. This way all new CAS users get Subscriber accounts, and any existing WordPress admins can still use their CAS credentials to log in.

Please note that this will still create a WordPress account for each new CAS user that logs in, but they will not have any permissions beyond Subscriber.**

This is how I currently have it set up which I think works perfectly. I selected "none" for new CAS users.

So the scenario is:
Admin A logs in with CAS and is able to view the site.
Admin A is unable to access dashboard while logged in with CAS.
When Admin A tries to access dashboard, Wordpress authentication login page must show up.
(hope this makes it a bit clearer)

**Comment by figureone** [comment]
Yeah that last scenario can't happen; Authorizer basically just links CAS logins with WordPress accounts (via the common email address on both). Why would you want to prevent **Admin A** from their normal capabilities based on which way they logged in? Doesn't seem to make sense.

**Comment by pkarjala** [comment]
The purpose of Authorizer is to facilitate login to a WordPress user by using CAS (or LDAP or Google) as an authentication method.  In order to have access control, all users (whether logged in using WordPress itself, or through Authorizer) need to have a WordPress account--otherwise WordPress will have no understanding of how it is supposed to grant view permissions with no WordPress account present, and just treat them as a guest to the site who hasn't logged in.

It would be better to create a role that you wish to have limited permissions (such as the aforementioned "Subscriber" role), then assign users who log in with CAS to that role.  Then create your admin users and give them the Admin or Super Admin role, which allows them to access the dashboard.

You can also get other plugins that will limit which roles can access the WordPress dashboard while logged in--again, these require that the user logging in have a WordPress account.

Regardless, you should be able to make it work with the `none` role assignment as @figureone pointed out.  Just note that you will not be able to avoid creating a WordPress account in any case.
